# Generated by Django 5.2.3 on 2025-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_careerenquiry_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerenquiry',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
