# Generated by Django 5.2.3 on 2025-07-14 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_careerenquiry_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerenquiry',
            name='phone',
        ),
    ]
