# Generated by Django 5.2.4 on 2025-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_careerenquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
